# Generated by Django 4.2 on 2023-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('R', 'Resort'), ('V', 'Villa'), ('H', 'Hotel')], max_length=2),
        ),
    ]
