# Generated by Django 4.2 on 2023-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('L', 'Luxury'), ('S', 'Standard')], max_length=4),
        ),
    ]
